# Generated by Django 3.2.7 on 2021-12-19 18:28

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smallbusinessapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='businessdata',
            name='smallbusine_busines_c15d8e_idx',
        ),
        migrations.AddIndex(
            model_name='businessdata',
            index=django.contrib.postgres.indexes.GinIndex(fields=['business_name'], name='smallbusine_busines_c0c169_gin'),
        ),
    ]
