# Generated by Django 3.2.7 on 2021-12-19 18:35

from django.db import migrations, models
from django.contrib.postgres.operations import BtreeGinExtension


class Migration(migrations.Migration):

    dependencies = [
        ('smallbusinessapp', '0002_auto_20211219_1228'),
    ]

    operations = [
        BtreeGinExtension(),
        migrations.RemoveIndex(
            model_name='businessdata',
            name='smallbusine_busines_c0c169_gin',
        ),
        migrations.AddIndex(
            model_name='businessdata',
            index=models.Index(fields=['business_name'], name='smallbusine_busines_c15d8e_idx'),
        ),
    ]
