# Generated by Django 3.2.7 on 2021-12-19 19:11

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations
from django.contrib.postgres.operations import BtreeGinExtension

class Migration(migrations.Migration):

    dependencies = [
        ('smallbusinessapp', '0004_auto_20211219_1252'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='businessdata',
            name='smallbusine_sv_62f516_gin',
        ),
        migrations.RemoveField(
            model_name='businessdata',
            name='sv',
        ),
        migrations.AddField(
            model_name='businessdata',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='businessdata',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='smallbusine_search__cbb535_gin'),
        ),
    ]
