# Generated by Django 3.2.7 on 2021-12-19 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smallbusinessapp', '0005_auto_20211219_1311'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='businessdata',
            name='smallbusine_search__cbb535_gin',
        ),
        migrations.RemoveField(
            model_name='businessdata',
            name='search_vector',
        ),
    ]
