# Generated by Django 3.2.7 on 2021-12-21 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smallbusinessapp', '0006_auto_20211219_1447'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='businessdata',
            name='smallbusine_busines_d39f38_idx',
        ),
        migrations.AddIndex(
            model_name='businessdata',
            index=models.Index(fields=['business_name'], name='smallbusine_busines_c15d8e_idx'),
        ),
    ]
