# Generated by Django 3.2.7 on 2022-02-02 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smallbusinessapp', '0008_auto_20220107_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateIndustryRevenueAverages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.TextField()),
                ('naics_code', models.TextField()),
                ('avg_revenue', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ZipCodeIndustryRevenueAverages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.TextField()),
                ('naics_code', models.TextField()),
                ('avg_revenue', models.TextField()),
            ],
        ),
        migrations.AddIndex(
            model_name='zipcodeindustryrevenueaverages',
            index=models.Index(fields=['naics_code', 'zip_code'], name='smallbusine_naics_c_e38d57_idx'),
        ),
        migrations.AddIndex(
            model_name='zipcodeindustryrevenueaverages',
            index=models.Index(fields=['zip_code'], name='smallbusine_zip_cod_ed29a0_idx'),
        ),
        migrations.AddIndex(
            model_name='zipcodeindustryrevenueaverages',
            index=models.Index(fields=['naics_code'], name='smallbusine_naics_c_b7bf11_idx'),
        ),
        migrations.AddIndex(
            model_name='stateindustryrevenueaverages',
            index=models.Index(fields=['naics_code', 'state'], name='smallbusine_naics_c_be244d_idx'),
        ),
        migrations.AddIndex(
            model_name='stateindustryrevenueaverages',
            index=models.Index(fields=['state'], name='smallbusine_state_74cf5b_idx'),
        ),
        migrations.AddIndex(
            model_name='stateindustryrevenueaverages',
            index=models.Index(fields=['naics_code'], name='smallbusine_naics_c_730413_idx'),
        ),
    ]
