# Generated by Django 3.2.7 on 2022-02-03 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smallbusinessapp', '0009_auto_20220202_1756'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='businessdata',
            name='smallbusine_busines_c2367f_idx',
        ),
        migrations.AddIndex(
            model_name='businessdata',
            index=models.Index(fields=['business_name', 'naics_name', 'revenue_estimate', 'num_employees', 'naics_name', 'address', 'state'], name='smallbusine_busines_71b381_idx'),
        ),
    ]
