# Generated by Django 3.2.7 on 2022-02-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smallbusinessapp', '0013_auto_20220204_1645'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='businessdata',
            index=models.Index(fields=['zip_code_int'], name='smallbusine_zip_cod_b9eb1f_idx'),
        ),
    ]
