# Generated by Django 3.2.7 on 2022-02-08 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smallbusinessapp', '0014_businessdata_smallbusine_zip_cod_b9eb1f_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='zipcodeindustryrevenueaverages',
            name='smallbusine_naics_c_e38d57_idx',
        ),
        migrations.RemoveIndex(
            model_name='zipcodeindustryrevenueaverages',
            name='smallbusine_zip_cod_ed29a0_idx',
        ),
        migrations.RemoveIndex(
            model_name='zipcodeindustryrevenueaverages',
            name='smallbusine_naics_c_b7bf11_idx',
        ),
    ]
