# Generated by Django 3.2.7 on 2022-02-09 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smallbusinessapp', '0018_auto_20220208_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdata',
            name='percentile_industry',
            field=models.FloatField(default=0),
        ),
    ]
