# Generated by Django 3.2.7 on 2022-02-11 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smallbusinessapp', '0019_businessdata_percentile_industry'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='businessdata',
            index=models.Index(fields=['naics_code'], name='smallbusine_naics_c_6de661_idx'),
        ),
    ]
