# Generated by Django 3.2.7 on 2022-02-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smallbusinessapp', '0021_auto_20220210_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateIndustryEmployeesAverages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.TextField()),
                ('naics_code', models.TextField()),
                ('avg_employees', models.TextField()),
            ],
        ),
        migrations.AddIndex(
            model_name='stateindustryemployeesaverages',
            index=models.Index(fields=['naics_code', 'state'], name='smallbusine_naics_c_b15e45_idx'),
        ),
        migrations.AddIndex(
            model_name='stateindustryemployeesaverages',
            index=models.Index(fields=['state'], name='smallbusine_state_459920_idx'),
        ),
        migrations.AddIndex(
            model_name='stateindustryemployeesaverages',
            index=models.Index(fields=['naics_code'], name='smallbusine_naics_c_d26324_idx'),
        ),
    ]
